<?php
/** @var \Magento\Framework\View\TemplateEngineInterface $this */
/** @var \Adam\WidgetsExample\Block\Widget\Test $block */
/** @var \Magento\Csp\Api\InlineUtilInterface $csp */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<h3><?= $escaper->escapeHtml($block->getData('title')) ?></h3>
<h3><?= $escaper->escapeHtml(__('Size:')) ?> <?= $escaper->escapeHtml($block->getData('size')) ?></h3>
<?php if ($block->getDescription()): ?>
    <p><?= $escaper->escapeHtml($block->getDescription()) ?></p>
<?php endif; ?>
